### ISSUE TITLE
Configurable backpack status effect string

### ISSUE THREAD

**Issue by shudnal** [Vapok/AdventureBackpacks#104]
Pls make string statusEffects.Effect.m_name at Assets.Backpacks.UpdateStatusEffects() configurable.
It's so long and spammy entry at the effect list.
statusEffects.Effect.m_name = $"{backpackName} $vapok_mod_level {backpackQuality} $vapok_mod_effect";
I can set $vapok_mod_effect to "" but not $vapok_mod_level  as it breaks Extensions.InventoryExtensions.IsBackPackInventory()

I don't think anyone needs to know their backpack quality all the time.
As we can't equip more than one backpack all the info except backpack name and icon is irrelevant.

I couldn't find any string comparison on Effect.m_name so it looks safe.
As a simple solution string could be localized whole with {0} and {1} parameters for name and quality.

**Comment by Vapok** [comment]
I'm aligned with this feeling.  I'll look and see what I can do next time I have the code open.

**Comment by Vapok** [comment]
This will be implemented in release 1.6.23
