### ISSUE TITLE
Unable to load World.

### ISSUE THREAD

**Issue by DerpyPandaKitty** [Vapok/AdventureBackpacks#105]
After extensive testing to figure out what mod was causing the issue this was the only mod that put out errors.

Version is Current Stable Release Steam. R2Modmanager was used and Manual install was also attempted to same errors.

I get this when game loads with this mod only.

[Error  : Unity Log] MissingMethodException: StatusEffect ObjectDB.GetStatusEffect(string)
Stack trace:
ItemManager.PrefabManager.Patch_ObjectDBInit (ObjectDB __instance) (at <6ff225bf58af4b23b00f9294ae14e63c>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::Awake>(ObjectDB)
UnityEngine.GameObject:AddComponent()
FejdStartup:SetupObjectDB()
FejdStartup:DMD<FejdStartup::Start>(FejdStartup)

[Error  : Unity Log] MissingMethodException: StatusEffect ObjectDB.GetStatusEffect(string)
Stack trace:
ItemManager.PrefabManager.Patch_ObjectDBInit (ObjectDB __instance) (at <6ff225bf58af4b23b00f9294ae14e63c>:0)
(wrapper dynamic-method) ObjectDB.DMD<ObjectDB::CopyOtherDB>(ObjectDB,ObjectDB)
FejdStartup.SetupObjectDB () (at <447b19510f604ca3807cd6cce3a7c1ef>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

This Error when I try to load up a world.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FejdStartup.OnWorldStart () (at <447b19510f604ca3807cd6cce3a7c1ef>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.UI.Button.Press () (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by Vapok** [comment]
Hi Derpy!  Thanks. This is all set and working
 Just released on the mod stores!

Thanks!
