### ISSUE TITLE
Backpack Inventory Modal Does Not Display

### ISSUE THREAD

**Issue by Morggo** [Vapok/AdventureBackpacks#106]
**Describe the bug**

When installed, player presses 'i' to call the backpack inventory modal to view and interact with contents.  Inventory opens as expected and all other actions appear normal.  The player's game inventory screen indicates the weight limit increase due to pack, however player cannot see visually the modal panel with the backpack slots and is unable to interact with items and backpack.

Notes:
1. This is a hosted server with Valheim+
2.  We do use Valheim Minus patcher mod to allow Bepinex but disable/unload V+
3.  Other players are using AdventureBackpacks with no issues.

**To Reproduce**
1.  Player installed AdventureBackpacks on client using R2modman
2.  Player loads valheim using R2modman 'start modded'
3.  Game loads correctly.
4.  Player gathered ingredients for Rugged Backpack
5.  Player crafted and equipped Rugged backpack
6.  Player pressed 'i' to view backpack slots
7.  Player inventory opened, but no backpack modal displayed. (however player's weight capacity increased by 10)

**Expected behavior**
Like other server players, expected backpack contents to display.

**Mod List (please list your mods that are being used):**
  Player uses the following mods: EquipmentAndQuickSlots, Cats, AdventureBackpacks (and bepinex ofcourse).  All have been reinstalled including R2modman to be sure latest Hildir updates.

Cats is server-side and dll is installed correctly and working.

**Additional context**

Thank you for taking the time to review!!!  This is a brilliant mod and look forward to all my players using it!!  Hoping it is just a mistake on our end.   Tonight I plan to have the player completely uninstall and reinstall their mods just to be certain unless you identify a clear issue.   I can try to obtain a log tonight if that may assist.

**Comment by Vapok** [comment]
I'll need your LogOutput.log if you don't mind from a session where you had the issue

**Comment by Morggo** [comment]
OKAY!.. Figured it out.  Player had remapped their keys... and changed the normal inventory call from TAB to i.

Changing it back to default mappings allowed the backpacks to function as intended.

So, only item to note here is to warn that remapping default keys could impact functionality.

Thank you again for an awesome mod.. we're off to adventure and good to close this ticket.

**Comment by Vapok** [comment]
Glad to hear!  Thanks!
