### ISSUE TITLE
AzuCraftyBoxes Integration

### ISSUE THREAD

**Issue by searica** [Vapok/AdventureBackpacks#110]
I play with AzuCraftyBoxes to allow me to build and craft using resources from nearby containers and although I have tried configuring it to find the backpacks from this mod based on their item ids, it can't seem to find resources inside of backpacks.

It would be great if the backpack protection inventory guard was modified to all AzuCraftyBoxes to pull resources from backpacks while crafting, much like how it lets Quick Stack Store deposit them.

Alternatively, if the item IDs for spawning the backpacks are actually different than the internal IDs for the containers associated with the backpack them simply listing them in the readme so AzuCraftyBoxes can be configured to find them could be great solution as well. I did search through the repo on github but couldn't discern if there were separate container IDs (not very familiar with C# though).

Anyways, thanks for the great mod!

**Comment by Vapok** [comment]
Hi @searica,

In the next release of Adventure Backpacks 1.6.23, I'm making a change where the equipped backpack will be available as a Container on the Player object at all times.  If the backpack is NOT equipped, then the Container will still exist, just with an empty inventory.  Once a backpack is reequipped, it will provide it's inventory to anything that is looking for it.

This is only half of the integration. You'll want to let @Azumattdev know that he'll need to make a change to Crafty Boxes to look and see if a Container is on the Player, and if so add that to his list of Containers (if it's not automatically being picked up).

**Comment by AzumattDev** [comment]
We have talked about it. I'll see what I need to do (if anything)
