### ISSUE TITLE
Unity console error during startup on Valheim 0.217.22

### ISSUE THREAD

**Issue by KaliRanya** [Vapok/AdventureBackpacks#117]
**Describe the bug**
On the current version of Valheim (0.217.22) patched on 2023/10/05, starting Valheim with Adventure Backpacks loaded throws an error in the Unity console.

**To Reproduce**
1. Install Valheim 0.217.22, AdventureBackpacks 1.6.27, and BepInExPack 5.4.2200.
2. Run Valheim with BepInEx and observe the Unity console. An error logs out. When you reach the main screen, any previously loaded character will not appear, with the placeholder "Ragnar" if you click to start a game.
3. Roll back to previous stable Valheim using the `default_old` beta branch; install BepInExPack 5.4.2105.
4. Run Valheim with BepInEx and check the Unity console again. With these versions, no error appears.

**Expected behavior**
Error free console. Possible this doesn't have functional impact, I haven't yet been able to tell, but worth investigating!

**Screenshots**
The exact error I see:
```
[Error  : Unity Log] MissingFieldException: Field 'FejdStartup.m_connectionFailedError' not found.
Stack trace:
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::ShowConnectError>(FejdStartup,ZNet/ConnectionStatus)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)
```

**Mod List (please list your mods that are being used):**
I first spotted this using a fairly extensive list, but while troubleshooting was able to reproduce the error with nothing installed except Adventure Backpacks and its prereq.

**Comment by Vapok** [comment]
This was updated fairly quickly after you posted this a few weeks ago. Shouldn't be an issue.
