### ISSUE TITLE
Issue loading plugin after latest update

### ISSUE THREAD

**Issue by Aecnoril** [Vapok/AdventureBackpacks#124]
The plugin currently breaks some things on server/client load. 

Start the game or a dedicated server and be greeted with this error:
```
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type ZInput and name GetKeyDown and parameters (UnityEngine.KeyCode)
[Error  :vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext] InventoryGui.Update Transpiler Failed To Patch
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedHideBackpackMethod True
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedShowBackpackMethod True
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedDetectInputHideMethod False
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedDetectInputShowMethod True
[Error  :vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext] Please inform Mod Author.
```

after which the console is filled with
`[Error  : Unity Log] MissingMethodException: Method not found: bool .ZInput.GetKeyDown(UnityEngine.KeyCode)`

Tested with only the backpacks mod installed, same results

I think it's because of the latest update adding controller input, it's possible they switched over to the new Unity Input Manager or simply changed how it's implemented which gave me relatable errors on another Unity project I'm working on, but that's just a guess/pointer.

**Comment by Taaikorsie** [comment]
I have the same issue.

**Comment by MisterEffWord** [comment]
Can confirm, error fires off upon starting the game. After disabling mod, no red text in game log.

**Comment by Defee** [comment]
Can you make a contribute guidance as well? for example how do you get the ServerSync.dll and how you get the APIManager.dll

**Comment by Aecnoril** [comment]
@Defee I think you're getting the wrong picture here, as those questions are entirely irrelevant

**Comment by tobbiusness** [comment]
Experiencing the same. Apart from log spam (and performance loss from it), the only downside is I can't open my inventory using a controller.

**Comment by Narolth** [comment]
Adding that I'm seeing this also.

`[Info   :   BepInEx] Loading [Adventure Backpacks 1.7.5]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type ZInput and name GetKeyDown and parameters (UnityEngine.KeyCode)
[Error  :vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext] InventoryGui.Update Transpiler Failed To Patch
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedHideBackpackMethod True
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedShowBackpackMethod True
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedDetectInputHideMethod False
[Warning:vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext]  patchedDetectInputShowMethod True
[Error  :vapok.mods.adventurebackpacks] [AdventureBackpacks.Patches.InventoryGuiPatches+InventoryGuiUpdateTranspiler+<Transpiler>d__0.MoveNext] Please inform Mod Author.`

**Comment by averad** [comment]
#125 has been created by OrianaVenture as a suggested fix for the issue.

**Comment by Narolth** [comment]
@Vapok PR #125

**Comment by averad** [comment]
ℹ️ Commenting to attach discord link to issue

Discord: [Vapok's Mod's Community](https://discord.gg/5YAJkRFBXt)

Beta Patch/Release has been posted on Discord. Feedback has been requested from Dev.

**Comment by Vapok** [comment]
Fixed and released.
