### ISSUE TITLE
Repo out of sync with Thunderstore releases

### ISSUE THREAD

**Issue by ghstwhl** [Vapok/AdventureBackpacks#126]
**Describe the bug**
Thunderstore is showing the release as 1.7.6, while this repo is at 1.7.1
Is this codebase being maintained somewhere else?  Where can we go to see release notes and what is being fixed/added/updated?

**To Reproduce**
1. Look at [Thunderstore release version](https://valheim.thunderstore.io/package/Vapok/AdventureBackpacks/)
2. Look at [repo release version](https://github.com/Vapok/AdventureBackpacks/releases)

**Expected behavior**
I would expect the releases to be in sync.

**Additional context**
Thank you for the amazing work!

**Comment by Vapok** [comment]
The releases aren't up to date.  But you can see the 1.7.6 branch.
