### ISSUE TITLE
Incompatible with Equipment and Quickslots?

### ISSUE THREAD

**Issue by ReFleXzZ** [Vapok/AdventureBackpacks#132]
**Describe the bug**
When both mods "Equipment and Quickslots" and "AdventureBackpacks" are activated, Im stuck on the loading screen, even though the console says I'm ingame.

**To Reproduce**
1. Activate both mentioned mods
2. try to login with any character

**Expected behavior**
I expect the game to load und throw me out of the loading screen.

**Screenshots**

![image](https://github.com/user-attachments/assets/1b17a3a6-43f3-4b62-9256-61f83587aa74 "Can open the menu, even though I'm still at the loadingscreen")

<img width="675" alt="image" src="https://github.com/user-attachments/assets/cd88f029-4e0b-49eb-9b0e-c4fca9c84a62">

**Mod List (please list your mods that are being used):**

Player log:

[Player.log](https://github.com/user-attachments/files/17610381/Player.log)

- denikson-BepInExPack_Valheim
- Azumatt-Official_BepInEx_ConfigurationManager
- GoldenJude-Blacksmiths_tools
- AllTheHeims-EpicLootPatching_AdventureBackpacks
- CW_Jesse-BetterNetworking_Valheim
- ValheimModding-HookGenPatcher
- ValheimModding-Jotunn
- NoPetRides-NoPetRides_ModUtils
- WackyMole-WackysDatabase
- shudnal-TradersExtended
- blacks7ar-RenegadeVikings
- ishid4-BetterArchery
- SpikeHimself-XPortal
- OdinPlus-TeleportEverything
- Azumatt-BetterWards
- Roses-SmarterContainers
- rendl0449-CraftFromContainers
- Goldenrevolver-Quick_Stack_Store_Sort_Trash_Restock
- MathiasDecrock-PlanBuild
- aedenthorn_nexus-AutoFeed
- JewelHeim-Magic_Crystal_Table
- RockerKitten-BoneAppetit
- Digitalroot-Triple_Bronze_JVL
- Therzie-Warfare
- Therzie-Armory
- ValadrielTheMad-ValadrielsMadArmory
- GoldenJude-Judes_Equipment
- Goldenrevolver-Obtainable_Stone_Pickaxe_and_Upgradeable_Antler_Pickaxe
- RandyKnapp-EpicLoot
- Vapok-AdventureBackpacks
- OdinPlus-BetterLanterns
- VikingGlory-ChestReloaded
- plumga-Clutter
- NexusTransfer-ValheimRAFT
- OdinPlus-OdinCampsite
- OdinPlus-OdinTrainingPlace
- OdinPlus-OdinsHorsePen
- OdinPlus-OdinHorse
- OdinPlus-OdinArchitect
- Marlthon-OdinShipPlus
- OdinPlus-BeeQueen
- BetterUI_ForeverMaintained-BetterUI_ForeverMaintained
- RandyKnapp-EquipmentAndQuickSlots
- RustyMods-Seasonality
- RustyMods-Seasonality_HD_Texture_Pack

EDIT: correction of list
Unfortunately the modlist in my r2modman profile contained all installed mods, even those which werent active at that time.

EDIT 2:
also happens whe deactivated "BetterUI_ForeverMaintained-BetterUI_ForeverMaintained"

EDIT 3:
deactivated AdventureBackpacks and activated Backpacks by Smoothbrain, and now the loading screen unloads. I'd still like to play with your mod though :(

**Additional context**
No additional context to be mentioned

**Comment by Vapok** [comment]
Hi @ReFleXzZ,

I actually develop against Equipment and Quickslots and Epic Loot to ensure compatibility, so I know that Adventure Backpacks has for a long time had total support of EAQS.

My assumption is that you have other errors going on.  I'll need the full LogOutput.txt though to be able to diagnose the errors that might be coming up.

If you'd like to provide your log, that'd be great.

**Comment by Vapok** [comment]
Actually, just realized you put the log in there.  You are running the wrong version of Adventure Backpacks.

This log shows:

[Info   :   BepInEx] Loading [Adventure Backpacks 1.7.5]

You should be running 1.7.7.

**Comment by ReFleXzZ** [comment]
That's interesting, sice I tested this after r2modman asked me about the update. I Updated it already and in the modmanager it was shown "1.7.7".

**Comment by ReFleXzZ** [comment]
Reinstalled all mods and log still says, I'm on 1.7.5

![image](https://github.com/user-attachments/assets/73bad597-a958-46c0-a190-9b7d72e99b26)

**Comment by Vapok** [comment]
Yeah I dunno... I use r2modman and it works just fine.  Something in your profile is trying to load an old version though.

**Comment by Vapok** [comment]
You know.. one second.

**Comment by Vapok** [comment]
I forgot to increment the version number... hang on.

**Comment by Vapok** [comment]
I'll be releasing 1.7.8 in a few minutes to fix the version issue.

But YOUR issue appears to be coming from Smoothbrain's Blacksmithing based on the error above.

![image](https://github.com/user-attachments/assets/0070e2e0-198c-4138-9531-5508fb7a1a74)
