### ISSUE TITLE
 Valheim on MacOS M1

### ISSUE THREAD

**Issue by pavluk** [Vapok/AdventureBackpacks#136]
Adding a mod to Valheim on MacOS M1 breaks the game, while other mods work correctly
<img width="1670" alt="изображение" src="https://github.com/user-attachments/assets/c608b7b7-538c-400c-a371-19aa50c76dcb">

Logs:
```
[Message:   BepInEx] BepInEx 5.4.23.2 - Valheim (11/6/2024 4:44:09 PM)
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, MacOS
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2022.3.50f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Adventure Backpacks 1.7.9]
[Message:   BepInEx] Chainloader startup complete
```

**Comment by Vapok** [comment]
You are not running the proper Valheim BepInex version.

Please make sure you are running the BepInEx for Valheim off of Thunderstorm

**Comment by Vapok** [comment]
I don't know what to do about that.  Valheim BepInEx has been working for a long time 

Could be the game?  I've tested on MacOS and Windows, And Linux, seems to be working fine.

I will need the full Log output to have a chance to see what's up.

Please provide the log for the version running on Valheim BepInex.  Vanilla BepInEx won't work.
