### ISSUE TITLE
Explorer's Whipsack resets the effects when you use tools/weapons.

### ISSUE THREAD

**Issue by rmbeon** [Vapok/AdventureBackpacks#19]
**Describe the bug**
When Explorer's Whipsack [upgrade level 4] is equipped: whenever you use any tools or weapons it resets the effects added by the backpack - so it respawns wisps constantly, most noticeable while switching the hammer on/off.

**To Reproduce**
1. Equip explorer's whipsack
2. Equip any tool or weapon
3. See error

**Expected behavior**
Effect stays on whether you use any tools/weapons or not.

**Screenshots**
Can't screenshot this particular issue, the description should be enough

**Mod List (please list your mods that are being used):**
[mods.zip](https://github.com/Vapok/AdventureBackpacks/files/10528265/mods.zip)

**Additional context**
There is also a visual issue with the Bloodbag Wetpack - the backpack belts are sticking out pretty significantly.

**Comment by Vapok** [comment]
Oh interesting....  I think I know what this is.. Thanks for the report.

**Comment by Vapok** [comment]
This has been fixed in 1.5.1!
