### ISSUE TITLE
i18n of Base Game doesn't work since last update

### ISSUE THREAD

**Issue by FirePowi** [Vapok/AdventureBackpacks#24]
**Describe the bug**
Variables have their variable names instead of the values since last update

**To Reproduce**
1·Set the game in French (for exemple)
2·Start the game modded

*Using Thunderstore Mod Manager

**Expected behavior**

**Screenshots**
![20230129154355_1](https://user-images.githubusercontent.com/14030913/215334064-3286d56c-ae2c-4e73-b713-b3837962b47b.jpg)

**Mod List (please list your mods that are being used):**
- AdventureBackpacks by Vapok
- BepInExPack_Valheim by denikson 

**Additional context**
Worked fine before last update

**Comment by Vapok** [comment]
Yep, Thanks someone else reported this for french. It's because of invalid characters. I have an update coming out shortly that will fix this.

**Comment by Vapok** [comment]
This is now fixed in version 1.5.4

**Comment by FirePowi** [comment]
Thank you!
