### ISSUE TITLE
VNEI search bar locks interface/soft locks game

### ISSUE THREAD

**Issue by DaltonGoesFast** [Vapok/AdventureBackpacks#35]
If you're using VNEI, and use the search bar and press 'i' in the search bar, it soft locks the game. The HUD disappears, but the simulation continues. The player can't move or do anything. Can't even press escape to open the menu, but there is still access to console commands. I just run the save command and ALT+F4. This issue doesn't seem to affect clients tho. 
[LogOutput.log](https://github.com/Vapok/AdventureBackpacks/files/10571190/LogOutput.log)

**Comment by Vapok** [comment]
In the Adventure Bags configuration, disable the Local Setting called "Close Inventory".   This will prevent that lock up.
