### ISSUE TITLE
fish in backpack on load cause an error in log

### ISSUE THREAD

**Issue by carpenteer** [Vapok/AdventureBackpacks#46]
**Describe the bug**
For **each** fish in a worn backpack, upon character load, the following error appears once in the log:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Fish.GetPointDepth (UnityEngine.Vector3 p) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.RandomizeWaypoint (System.Boolean canHook) (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.onCollision () (at <035307060cbb4b30b916cd82ebd80490>:0)
Fish.OnCollisionEnter (UnityEngine.Collision collision) (at <035307060cbb4b30b916cd82ebd80490>:0)

**To Reproduce**
1. Catch a fish
2. Put it in your backpack
3. Log out of the game
4. Log back in.

**Expected behavior**
I didn't expect a bunch of red error text in my bep window, lol

**Additional context**
This appears to cause no further issues, I just figured you might be interested.

**Comment by Vapok** [comment]
This smells fishy....

**Comment by Vapok** [comment]
Can't reproduce.  I've tried spawned fish, caught fish, and picked up fish.  I've analyzed the Fish.GetPointDepth, and can't see any way or reason why this would even come close to interacting with player inventory or backpacks.
