### ISSUE TITLE
Armor stand duplicates items in backpacks

### ISSUE THREAD

**Issue by RampagingRampage** [Vapok/AdventureBackpacks#67]
**Describe the bug**
Duping items in the backpack when using armor stands

**To Reproduce**
1. Place a backpack with items in it onto an armor stand.
2. All items will be thrown out onto the ground while also staying in the backpack. Duping the items.

**Comment by Vapok** [comment]
This is confirmed.

**Comment by Vapok** [comment]
This has been fixed and resolved in Release 1.6.5
