### ISSUE TITLE
Backpack won't open

### ISSUE THREAD

**Issue by Imrald** [Vapok/AdventureBackpacks#81]
**Describe the bug**
Pressing I doesn't open the backpack

**To Reproduce**
1. Right click to equip backpack
2. Click I to open
3. Backpack doesn't open

**Expected behavior**
Seeing backpack inventory.

**Mod List (please list your mods that are being used):**
[Player.log](https://github.com/Vapok/AdventureBackpacks/files/10959450/Player.log)

**Comment by Vapok** [comment]
Please update to 1.6.10 version of the backpack.
