### ISSUE TITLE
Issue: "Drop Backpack" key triggers when entering sign text

### ISSUE THREAD

**Issue by AiriErminia** [Vapok/AdventureBackpacks#90]
Hi, just wanted to let you know that the Quickdrop Backpack function still occurs when typing in the sign/portal windows.

To reproduce:
1. equip a backpack
2. build a sign or portal
3. press whichever key "Quickdrop Backpack" is assigned to.
Your backpack will be unintentionally quickdropped.

Maybe related (should I open a new issue?) but even though the "Open Backpack" and inventory keys (with Open with Inventory) don't open the backpack while the enter text window is open, they'll queue and open up right afterwards. Not nearly as problematic, but still unintentional and annoying.

**Comment by Vapok** [comment]
This should be fixed as of 1.6.14.  I just solved this problem.

**Comment by Vapok** [comment]
Let me confirm about the quick drop key though.

**Comment by AiriErminia** [comment]
The queueing is definitely an improvement, I was wondering if that's what was going on. Thanks for being so on top of things!

**Comment by Vapok** [comment]
This has now been fixed in my development environment, and you'll see this deployed in the next update.

Interestingly enough, I also figured out how to stop the inventory queuing.  😄

**Comment by Vapok** [comment]
Fixed in 1.6.15
