### ISSUE TITLE
Polish Translations

### ISSUE THREAD

**Issue by GryfuPl** [Vapok/AdventureBackpacks#97]
{
  "vapok_mod_item_backpack_meadows": "Tornister",
  "vapok_mod_item_backpack_meadows_description": "Mały plecak zdolny pomieścić przedmioty.",

  "vapok_mod_item_backpack_blackforest": "Wytrzymały Plecak",
  "vapok_mod_item_backpack_blackforest_description": "Wytrzymały plecak, w komplecie z klamrami i delikatnymi skórzanymi paskami.",

  "vapok_mod_item_backpack_swamp": "Krwawy Wodoodporny Plecak",
  "vapok_mod_item_backpack_swamp_description": "Wytrzymały plecak uszczelniony przy użyciu wodoodpornych worków na krew.",

  "vapok_mod_item_backpack_mountains": "Arktyczny Plecak",
  "vapok_mod_item_backpack_mountains_description": "Arktyczny plecak, nadający się na długie wędrówki po górach.",

  "vapok_mod_item_backpack_plains": "Plecak ze Skóry Loxa",
  "vapok_mod_item_backpack_plains_description": "Plecak poszukiwaczy przygód wykonany z niezwykle wytrzymałej skóry loxa",

  "vapok_mod_item_backpack_mistlands": "Plecak Odkrywcy",
  "vapok_mod_item_backpack_mistlands_description": "Perfekcyjnie wykonany, mistyczny plecak. W komplecie z własnym pudełkiem do przechowywania. Nikt nie jest pewien, jak to działa.",

  "vapok_mod_item_rugged_backpack": "Stary Wytrzymały Plecak",
  "vapok_mod_item_rugged_backpack_description": "Wytrzymały stary plecak, w komplecie z klamrami i delikatnymi skórzanymi paskami.",

  "vapok_mod_item_arctic_backpack": "Srary Arktyczny Plecak",
  "vapok_mod_item_arctic_backpack_description": "Srary arktyczny plecak, w dalszym ciągu nadający się na długie wędrówki po górach.",

  "vapok_mod_no_inception1": "Nie rozgniewaj bogów.",
  "vapok_mod_no_inception2": "Zostałeś ostrzeżony.",
  "vapok_mod_no_inception3": "Rozgniewałeś bogów!",
  "vapok_mod_no_inception4": "Ehh... Thor wkrótce się z tobą rozprawi.",
  "vapok_mod_no_inception5": "Thor pozbawił cię mocy!!!",

  "vapok_mod_thor_saves_contents": "W tym plecaku były rzeczy. Thor zachował je dla ciebie.",
  
  "vapok_mod_useful_backpack": "Twój plecak sprawia wrażenie użytecznego.",
  "vapok_mod_you_droped_bag": "Upuściłeś plecak!",
  "vapok_mod_level": "Poziom",
  "vapok_mod_effect": "Efekt",
  "vapok_mod_quick_drop_unavailable": "Szybki Drop Niedostępny.",
  
  "vapok_mod_se_cold_immunity": "Odporność na zimno",
  "vapok_mod_se_frost_resistance": "Odporność na mróz",
  "vapok_mod_se_wet_resistance": "Odporność na wodę",
  
  "item_friendlyskeletonwand_spectralshroud_backpack": "Widmowy Całun Utrzymania"
}

**Comment by GryfuPl** [comment]
@rysson O kurde rzeczywiście mi się walnęło z tym srary, trochę późno było, dziękuję za zwrócenie uwagi.
Szczerze nie wiem, jak one w grze wyglądają, ale widząc, że jest też "stary arktyczny plecak" zdecydowałem się w obu miejscach nie tworzyć zamienników.
Stwierdziłem, że chce, żeby było jednolicie zimnoodporny brzmiało dziwnie xD

**Comment by rysson** [comment]
Czyli co, nanosimy uwagi na https://github.com/Vapok/AdventureBackpacks/pull/98/files?
Wtedy @Vapok będzie łatwiej zatwierdzić merge.

---

Sugesstion: comment and fix PR, @Vapok  could just accept  *Pull-Request*

**Comment by rysson** [comment]
@GryfuPl, ale ten „stary” to wziąłeś z konfiguracji, prawda?
Pytam, bo nazwy przedmiotów z pliku tłumaczeń nie mają „old”.

**Comment by GryfuPl** [comment]
Tak tłumaczyłem z wersji angielskiej https://github.com/Vapok/AdventureBackpacks/blob/main/AdventureBackpacks/Translations/English.json

Bo idąc nazwami plecaków po id, powinno być np. błotny plecak, plecak wspinaczkowy itp. więc raczej autor by tak je nazwał. Problem był w tym, że miały te same opisy to poszedłem w stronę stary.

Osobiście jakoś mi to tłumaczenie na górze nie przypadło do gustu "**_Misternie_** wykonany", "Nie kuś bogów.", "Ech... Thor wkrótce się tobą **_zaopiekuje_**", "**_Mocny_** plecak ze skóry loxa.", "W plecaku były _**tajemnicze**_ rzeczy. Thor zatrzymał je dla **_siebie_**." w oryginale dość, że nie ma mowy o _**tajemniczych**_ rzeczach to jest "for you"

Są też podobające mi się wyrażenia
- " w komplecie z własnym pudełkiem _**na drobiazgi**_. Nikt nie jest pewien, jak to działa." drugiego zdania zapomniałem dodać xD
- "Plecak na długie wyprawy po **_lodowych pustkowiach_**."
- "Szybka **_drzemka jest_** niedostępna." nie sądziłem, że chodzi o spanie

**Comment by GryfuPl** [comment]
Proponuje takie tłumaczenie

{
  "vapok_mod_item_backpack_meadows": "Tornister",
  "vapok_mod_item_backpack_meadows_description": "Mały plecak zdolny pomieścić kilka przedmiotów.",

  "vapok_mod_item_backpack_blackforest": "Skórzany Plecak",
  "vapok_mod_item_backpack_blackforest_description": "Skórzany plecak, w komplecie z klamrami i delikatnymi skórzanymi paskami.",

  "vapok_mod_item_backpack_swamp": "Krwawy Plecak",
  "vapok_mod_item_backpack_swamp_description": "Wodoodporny plecak uszczelniony przy użyciu worków na krew.",

  "vapok_mod_item_backpack_mountains": "Plecak Wspinaczkowy",
  "vapok_mod_item_backpack_mountains_description": "Plecak idealnie nadający się na długie wędrówki po górach.",

  "vapok_mod_item_backpack_plains": "Plecak ze Skóry Loxa",
  "vapok_mod_item_backpack_plains_description": "Plecak poszukiwaczy przygód wykonany z niezwykle wytrzymałej skóry loxa",

  "vapok_mod_item_backpack_mistlands": "Plecak Odkrywcy",
  "vapok_mod_item_backpack_mistlands_description": "Perfekcyjnie wykonany, mistyczny plecak. W komplecie z własnym pudełkiem na drobiazgi. Nikt nie jest pewien, jak to działa.",

  "vapok_mod_item_rugged_backpack": "Wytrzymały Plecak",
  "vapok_mod_item_rugged_backpack_description": "Wytrzymały plecak, w komplecie z klamrami i delikatnymi skórzanymi paskami.",

  "vapok_mod_item_arctic_backpack": "Arktyczny pleca",
  "vapok_mod_item_arctic_backpack_description": "Arktyczny plecak na długie wyprawy po lodowych pustkowiach.",

  "vapok_mod_no_inception1": "Nie rozgniewaj bogów.",
  "vapok_mod_no_inception2": "Zostałeś ostrzeżony.",
  "vapok_mod_no_inception3": "Rozgniewałeś bogów!",
  "vapok_mod_no_inception4": "Eh... Thor wkrótce się z tobą rozprawi.",
  "vapok_mod_no_inception5": "Thor pozbawił cię mocy!!!",

  "vapok_mod_thor_saves_contents": "W tym plecaku były rzeczy. Thor zachował je dla ciebie.",
  
  "vapok_mod_useful_backpack": "Twój plecak sprawia wrażenie użytecznego.",
  "vapok_mod_you_droped_bag": "Upuściłeś plecak!",
  "vapok_mod_level": "Poziom",
  "vapok_mod_effect": "Efekt",
  "vapok_mod_quick_drop_unavailable": "Szybka drzemka jest niedostępna.",
  
  "vapok_mod_se_cold_immunity": "Odporność na zimno",
  "vapok_mod_se_frost_resistance": "Odporność na mróz",
  "vapok_mod_se_wet_resistance": "Odporność na wodę",
  
  "item_friendlyskeletonwand_spectralshroud_backpack": "Widmowy Całun Utrzymania"
}

**Comment by rysson** [comment]
> Tak tłumaczyłem z wersji angielskiej https://github.com/Vapok/AdventureBackpacks/blob/main/AdventureBackpacks/Translations/English.json
> 
> Bo idąc nazwami plecaków po id, powinno być np. błotny plecak, plecak wspinaczkowy itp. więc raczej autor by tak je nazwał. Problem był w tym, że miały te same opisy to poszedłem w stronę stary.
> 
> Osobiście jakoś mi to tłumaczenie na górze nie przypadło do gustu "**_Misternie_** wykonany", "Nie **_kuś_** bogów.", "Ech... Thor wkrótce się tobą **_zaopiekuje_**", "**_Mocny_** plecak ze skóry loxa.", "W plecaku były _**tajemnicze**_ rzeczy. Thor zatrzymał je dla **_siebie_**." w oryginale dość, że nie ma mowy o _**tajemniczych**_ rzeczach to jest "for you"

Hmm... no dobra nie wszystkie określenia miały u mnie sens.
Choć „kuś”, „zaopiekuje się”  odbieram jako lekką ironię. Dobra, ”rozprawi” pasuje, zresztą o kuszenie nie będę kruszył kopii. Tylko pozwolę sobie na „ech”. (na wzór „ach” i „aha”).

> Są też podobające mi się wyrażenia
> 
> * " w komplecie z własnym pudełkiem _**na drobiazgi**_."
> * "Plecak na długie wyprawy po **_lodowych pustkowiach_**."

:-D

> **Edit:** Jednak nie chodzi o spanie a o szybkie rzucenie plecaka xD
> * "Szybka **_drzemka jest_** niedostępna." nie sądziłem, że chodzi o spanie

O! No pięknie, dzięki.
Także błędnie miałem  Thor zachował dla **siebie**.


- nie bardzo leży mi `Plecak Wspinaczkowy`, już bardziej „Górski”, jakoś zwięźlej brzmi
- ciągle nie jestem pewien `tornistra`, wiem, że formalnie pasuje, ale wybitnie mi kojarzy się z wyprawami; już bardziej torba (w sumie plecak też jest typem torby, aż sprawdziłem a wikipedii :-)) – niemniej na razie wrzucam Twoją propozycję
- bardzo mocno mi się podoba `Krwawy Plecak` – świetnie brzmi i oddaje jego budowę
- generalnie nazwy potoczne (tutaj plecak i jego określenie) w naszym języku piszemy z małej litery, ale też nie będę się upierał, potraktuję to jako nazwę własną
- także wyrazy z „x” na końcu w odmianie powinny mieć „ks” ale „loksa” jakoś mnie nie przekonuje i proponuję zostawić odstępstwo

Poprawiłem #98

**Comment by GryfuPl** [comment]
- Najwyżej, jeśli będę musiał zaktualizować tłumaczenie, to zmienię na „Górski”, bo rzeczywiście zwięźlej brzmi.
- Jeśli patrzyłem na odpowiedni przedmiot, no to jeden do jeden wygląda jak tornister, a one były stosowane w wojsku, więc no bardziej pasuje, a nawet jeśli będzie postrzegany za dziecięcy no to chyba dobrze, na początku Valheim też jest się takim dzieciakiem, który stawia pierwsze kroki
-Wiem, ale jakoś wygląda to dla mnie lepiej, gdy oba słowa zaczynają się wielką literą.
- No właśnie z tym miałem problem, bo nie wiem, czy jest określany w grze jako nazwa własna i go nie spolszczać, czy to robić a samo też „Plecak Loxa/Loksa” jakoś mi nie pasowało, brzmiał trochę, jak by należał do kogoś, a „ze skóry” chyba łatwiej się idzie domyślić, że chodzi o zwierzę.

**Comment by rysson** [comment]
Co do uwag, to się zgadzam i uwzględniłem. Do tornistra już się przekonałem :-D

Zerknij na #98, czy tak może być, są drobne różnice ale pytam czy nie protestujesz.
Dobrze by było ustalić czy obu nam pasuje takie tłumaczenie i wtedy poprosić autora o akceptację gotowego PR.
